from z3 import *
import torch
import numpy as np
import random
from typing import Optional, Tuple


# Flat (row*4+col) indices for the 8 kept cells
_KEPT_MASK = torch.tensor(
    [[1, 1, 0, 0],
     [1, 1, 0, 0],
     [0, 0, 1, 1],
     [0, 0, 1, 1]], dtype=torch.bool
)
_KEPT_FLAT_IDX = _KEPT_MASK.view(-1).nonzero(as_tuple=True)[0]  # [8]
 
# 10 swap pairs as flat indices [10, 2]
_SWAP_PAIRS_RAW = [
    ((0, 0), (0, 1)), ((0, 0), (1, 0)), ((1, 0), (1, 1)),
    ((0, 1), (1, 1)), ((0, 0), (1, 1)),
    ((2, 2), (2, 3)), ((2, 2), (3, 2)), ((3, 2), (3, 3)),
    ((2, 3), (3, 3)), ((2, 2), (3, 3)),
]
_SWAP_PAIRS = torch.tensor(
    [[r1 * 4 + c1, r2 * 4 + c2] for (r1, c1), (r2, c2) in _SWAP_PAIRS_RAW],
    dtype=torch.long,
)  # [10, 2]


class Sampler:
    """
    Generates SAT (valid) and UNSAT (invalid) 4x4 Sudoku boards.

    SAT boards: All 288 valid 4x4 Sudoku solutions are enumerated once via Z3
                and cached as a GPU tensor.

    UNSAT boards: Generated by taking a SAT board and introducing a single
                  constraint violation of a randomly chosen type:
                    - row:   two distinct cells in the same row are made equal
                    - col:   two distinct cells in the same column are made equal
                    - block: two distinct cells in the same 2x2 block are made equal
                  The violated cell *pair* is also randomised (not fixed to
                  positions 0 and 1), so the model cannot shortcut by only
                  checking specific cell pairs.

    Vectorised batch sampling runs entirely on GPU; a rejection loop replaces
    only the rare boards that accidentally remain valid after corruption.
    """

    # ------------------------------------------------------------------ #
    #  Initialisation                                                      #
    # ------------------------------------------------------------------ #

    def __init__(self):
        all_solutions = self._enumerate_all_sat_boards()          # np [288, 4, 4]
        self.sat_boards_cache = (
            torch.tensor(all_solutions, dtype=torch.long)
        )                                                          # [288, 4, 4]
        self.num_sat = len(self.sat_boards_cache)

        # Pre-project the cache to kept cells for fast lookup during the walk
        self._kept_cache = (
            self.sat_boards_cache.view(self.num_sat, 16)[:, _KEPT_FLAT_IDX]
        )  # [288, 8]

    # ------------------------------------------------------------------ #
    #  SAT board enumeration (runs once at construction)                  #
    # ------------------------------------------------------------------ #

    def _make_base_solver(self):
        """Return a Z3 Solver pre-loaded with all 4x4 Sudoku constraints."""
        s = Solver()
        X = [[Int(f"x_{i}_{j}") for j in range(4)] for i in range(4)]

        for i in range(4):
            for j in range(4):
                s.add(And(X[i][j] >= 1, X[i][j] <= 4))

        for i in range(4):
            s.add(Distinct(X[i]))
            s.add(Distinct([X[j][i] for j in range(4)]))

        for bi in [0, 2]:
            for bj in [0, 2]:
                block = [X[bi + di][bj + dj] for di in range(2) for dj in range(2)]
                s.add(Distinct(block))

        return s, X

    def _enumerate_all_sat_boards(self) -> np.ndarray:
        """Enumerate every valid 4x4 Sudoku solution (288 in total)."""
        s, X = self._make_base_solver()
        solutions = []

        while s.check() == sat:
            m = s.model()
            board = np.array(
                [[m.evaluate(X[i][j]).as_long() for j in range(4)] for i in range(4)], #type:ignore
                dtype=np.int64,
            )
            solutions.append(board)
            # Exclude this solution from future searches
            s.add(Or([X[i][j] != m.evaluate(X[i][j]) for i in range(4) for j in range(4)]))

        return np.array(solutions)   # [288, 4, 4]

    # ------------------------------------------------------------------ #
    #  Validity check (tensor, no Z3)                                     #
    # ------------------------------------------------------------------ #

    def tensor_check(self, boards: torch.Tensor) -> torch.Tensor:
        """
        Check validity by exact membership in the exhaustive SAT cache.

        Args:
            boards: [B, 4, 4] long tensor

        Returns:
            [B] bool tensor — True iff the board is a valid Sudoku solution.
        """
        sat_boards_cache = self.sat_boards_cache.to(boards.device)  # ensure same device
        with torch.no_grad():
            flat_boards = boards.view(boards.size(0), -1)          # [B, 16]
            flat_cache  = sat_boards_cache.view(self.num_sat, -1)  # [288, 16]
            # [B, 288] -> [B]
            matches = (flat_boards.unsqueeze(1) == flat_cache.unsqueeze(0)).all(dim=2)
            return matches.any(dim=1)

    # ------------------------------------------------------------------ #
    #  Vectorised UNSAT board generation                                  #
    # ------------------------------------------------------------------ #

    def _apply_violations(
        self,
        device: torch.device,
        boards: torch.Tensor,
        violation_type: torch.Tensor,
        row_i:   torch.Tensor,
        row_src: torch.Tensor,
        row_dst: torch.Tensor,
        col_j:   torch.Tensor,
        col_src: torch.Tensor,
        col_dst: torch.Tensor,
        bi:      torch.Tensor,
        bj:      torch.Tensor,
        blk_src: torch.Tensor,
        blk_dst: torch.Tensor,
    ) -> torch.Tensor:
        """
        Apply one of three violation types to each board in the batch.

        All index tensors have shape [B, K].  The boards tensor is cloned
        before modification so the cache is never mutated.

        Violation semantics
        -------------------
        row:   board[i, dst_col] = board[i, src_col]   (same row i)
        col:   board[dst_row, j] = board[src_row, j]   (same column j)
        block: board[bi, bj+blk_dst] = board[bi, bj+blk_src]  (same 2x2 block)
        """
        B, K = violation_type.shape
        result = boards.clone().float()          # [B, K, 4, 4]

        b_idx = torch.arange(B, device=device).unsqueeze(1).expand(B, K)
        k_idx = torch.arange(K, device=device).unsqueeze(0).expand(B, K)

        # --- Row violation ---
        boards_row = result.clone()
        src_val = boards[b_idx, k_idx, row_i, row_src]        # board[i, src_col]
        boards_row[b_idx, k_idx, row_i, row_dst] = src_val    # board[i, dst_col] = src_val

        # --- Col violation ---
        boards_col = result.clone()
        src_val = boards[b_idx, k_idx, col_src, col_j]        # board[src_row, j]
        boards_col[b_idx, k_idx, col_dst, col_j] = src_val    # board[dst_row, j] = src_val

        # --- Block violation ---
        # blk_src / blk_dst are offsets within the 2x2 block: values in {0, 1}
        boards_blk = result.clone()
        src_val = boards[b_idx, k_idx, bi, bj + blk_src]      # board[bi, bj+src]
        boards_blk[b_idx, k_idx, bi, bj + blk_dst] = src_val  # board[bi, bj+dst] = src_val

        is_row = (violation_type == 0)[..., None, None]        # [B, K, 1, 1]
        is_col = (violation_type == 1)[..., None, None]
        is_blk = (violation_type == 2)[..., None, None]

        result = torch.where(is_row, boards_row, result)
        result = torch.where(is_col, boards_col, result)
        result = torch.where(is_blk, boards_blk, result)

        return result.long()

    def _sample_violation_params(self, device: torch.device, batch_size: int, k: int):
        """
        Sample all randomised violation parameters in one place.

        Returns a dict of tensors, each of shape [batch_size, k].
        """
        T = batch_size * k   # total samples

        def t(*args, low=0, high=1):
            return torch.randint(low, high + 1, (T,), device=device).view(batch_size, k)

        # Which violation type: 0=row, 1=col, 2=block
        violation_type = torch.randint(0, 3, (T,), device=device).view(batch_size, k)

        # Row violation params: row index, source col, destination col (must differ)
        row_i   = t(low=0, high=3)
        row_src = t(low=0, high=3)
        row_dst = t(low=0, high=3)
        # Ensure src != dst by incrementing dst modulo 4
        row_dst = (row_src + 1 + torch.randint(0, 3, (T,), device=device).view(batch_size, k)) % 4

        # Col violation params: col index, source row, destination row (must differ)
        col_j   = t(low=0, high=3)
        col_src = t(low=0, high=3)
        col_dst = (col_src + 1 + torch.randint(0, 3, (T,), device=device).view(batch_size, k)) % 4

        # Block violation params: block origin (bi, bj), src/dst offsets within 2x2 (0 or 1)
        bi      = torch.randint(0, 2, (T,), device=device).view(batch_size, k) * 2   # 0 or 2
        bj      = torch.randint(0, 2, (T,), device=device).view(batch_size, k) * 2   # 0 or 2
        blk_src = t(low=0, high=1)
        blk_dst = 1 - blk_src   # always differ (flip between 0 and 1)

        return dict(
            violation_type=violation_type,
            row_i=row_i, row_src=row_src, row_dst=row_dst,
            col_j=col_j, col_src=col_src, col_dst=col_dst,
            bi=bi, bj=bj, blk_src=blk_src, blk_dst=blk_dst,
        )

    def _get_unsat_candidates(self, device: torch.device, batch_size: int, k: int) -> torch.Tensor:
        """
        Generate [batch_size, k, 4, 4] candidate UNSAT boards (not yet verified).
        """
        sat_boards_cache = self.sat_boards_cache.to(device)
        with torch.no_grad():
            indices = torch.randint(0, self.num_sat, (batch_size, k), device=device)
            boards  = sat_boards_cache[indices].clone().float()   # [B, K, 4, 4]
            params  = self._sample_violation_params(device, batch_size, k)
            return self._apply_violations(device, boards, **params)

    # ------------------------------------------------------------------ #
    #  Public batch samplers                                              #
    # ------------------------------------------------------------------ #

    def tensor_sat_sample_batch(
        self, device: torch.device, batch_size: int, k: int = 1
    ) -> torch.Tensor:
        """
        Sample [batch_size, k, 4, 4] valid Sudoku boards uniformly at random
        from the exhaustive solution cache.
        """
        sat_boards_cache = self.sat_boards_cache.to(device)  # ensure cache is on the same device
        with torch.no_grad():
            indices = torch.randint(0, self.num_sat, (batch_size, k), device=device)
            return sat_boards_cache[indices]   # [B, K, 4, 4]

    def tensor_unsat_sample_batch(
        self, device: torch.device, batch_size: int, k: int = 1, max_retries: int = 100
    ) -> torch.Tensor:
        """
        Sample [batch_size, k, 4, 4] *invalid* Sudoku boards.

        Uses a per-sample rejection loop: only the boards that accidentally
        remain valid (very rare) are regenerated, not the whole batch.

        Raises RuntimeError if the rejection loop fails to converge within
        max_retries iterations (indicates a bug in violation logic).
        """
        result = self._get_unsat_candidates(device, batch_size, k)          # [B, K, 4, 4]
        flat   = result.view(batch_size * k, 4, 4)
        still_valid = self.tensor_check(flat).view(batch_size, k)    # [B, K]

        for attempt in range(max_retries):
            if not still_valid.any():
                break

            # Indices of (batch, k) positions that are still accidentally valid
            bad_b, bad_k = still_valid.nonzero(as_tuple=True)        # each [N_bad]
            n_bad = len(bad_b)

            # Generate replacements only for the bad slots
            replacements = self._get_unsat_candidates(device, n_bad, 1).squeeze(1)  # [N_bad, 4, 4]
            result[bad_b, bad_k] = replacements
            still_valid[bad_b, bad_k] = self.tensor_check(replacements)

        else:
            raise RuntimeError(
                f"UNSAT sampling failed to converge after {max_retries} retries. "
                "Check violation logic."
            )

        return result   # [B, K, 4, 4]

    def batch_k_sample(self, device: torch.device, board_labels, batch_size: int, k: int = 1) -> torch.Tensor:
        board_labels = board_labels.to(device)  # ensure same device as cache

        sat_samples   = self.tensor_sat_sample_batch(device, batch_size, k)
        unsat_samples = self.tensor_unsat_sample_batch(device, batch_size, k)

        sat_mask   = (board_labels == 1)   # [B]
        unsat_mask = (board_labels == 0)   # [B]

        # Validate — catch unexpected label values early
        assert (sat_mask | unsat_mask).all(), \
            f"board_labels must be 0 or 1, got: {board_labels.unique().tolist()}"

        # Start from sat_samples, overwrite UNSAT positions
        result = sat_samples.clone()
        result[unsat_mask] = unsat_samples[unsat_mask]

        return result
    # ---------------------------------------------------------------------- #
    #  Walk: projection-based MCMC pseudo-label update                        #
    # ---------------------------------------------------------------------- #
 
    def walk(
        self,
        labels: torch.Tensor,
        board_labels: torch.Tensor,  # [B] — 1 for SAT, 0 for UNSAT
    ) -> torch.Tensor:
        """
        One step of the walk for both SAT and UNSAT boards.

        Args:
            labels:       [B, 4, 4] long tensor — current boards (values 1..4).
            board_labels: [B]       long tensor — 1 if SAT, 0 if UNSAT.

        Returns:
            [B, 4, 4] long tensor — updated boards.
        """
        B = labels.shape[0]
        device = labels.device

        with torch.no_grad():
            is_sat   = board_labels.bool()   # [B]
            is_unsat = ~is_sat               # [B]

            result = labels.clone()

            _swap_pairs = _SWAP_PAIRS.to(device)
            _kept_flat_idx = _KEPT_FLAT_IDX.to(device)

            _kept_cache = self._kept_cache.to(device)  # [288, 8]
            sat_boards_cache = self.sat_boards_cache.to(device)  # [288, 4, 4]

            # ----------------------------------------------------------------
            # SAT branch: swap → project → inverse-project via cache lookup
            # ----------------------------------------------------------------
            if is_sat.any():
                sat_idx    = is_sat.nonzero(as_tuple=True)[0].to(device)   # [S]
                sat_labels = labels[sat_idx]                     # [S, 4, 4]
                S          = sat_idx.shape[0]

                pair_idx  = torch.randint(0, 10, (S,), device=device)
                pair_flat = _swap_pairs[pair_idx]                # [S, 2]
                b_idx     = torch.arange(S, device=device)

                flat  = sat_labels.view(S, 16).clone()
                val_a = flat[b_idx, pair_flat[:, 0]].clone()
                val_b = flat[b_idx, pair_flat[:, 1]].clone()
                flat[b_idx, pair_flat[:, 0]] = val_b
                flat[b_idx, pair_flat[:, 1]] = val_a

                partial   = flat[:, _kept_flat_idx]              # [S, 8]
                matches   = (partial.unsqueeze(1) == _kept_cache.unsqueeze(0)).all(dim=2)
                has_match = matches.any(dim=1).to(device)                   # [S]
                best_idx  = matches.long().argmax(dim=1)
                proposals = sat_boards_cache[best_idx]      # [S, 4, 4]

                result[sat_idx[has_match]] = proposals[has_match]

            # ----------------------------------------------------------------
            # UNSAT branch: swap two cells → reject if accidentally SAT
            # ----------------------------------------------------------------
            if is_unsat.any():
                unsat_idx    = is_unsat.nonzero(as_tuple=True)[0]   # [U]
                unsat_labels = labels[unsat_idx]                      # [U, 4, 4]
                U            = unsat_idx.shape[0]

                pair_idx  = torch.randint(0, 10, (U,), device=device)
                pair_flat = _swap_pairs[pair_idx]                # [U, 2]
                b_idx     = torch.arange(U, device=device)

                flat  = unsat_labels.view(U, 16).clone()
                val_a = flat[b_idx, pair_flat[:, 0]].clone()
                val_b = flat[b_idx, pair_flat[:, 1]].clone()
                flat[b_idx, pair_flat[:, 0]] = val_b
                flat[b_idx, pair_flat[:, 1]] = val_a

                proposals   = flat.view(U, 4, 4)
                still_unsat = ~self.tensor_check(proposals)      # [U]

                result[unsat_idx[still_unsat]] = proposals[still_unsat]

        return result

    def naive_flip(
        self,
        labels: torch.Tensor,        # [B, 4, 4]  values 1..4
        board_labels: torch.Tensor,  # [B]         1=SAT, 0=UNSAT
    ) -> torch.Tensor:
        """
        Ablation-C baseline: unstructured single-cell digit-flip walk.

        For each board, picks one cell at random and assigns it a new digit
        drawn uniformly from {1,2,3,4} {current_digit}.  No projection or
        symmetry structure is used.

        SAT  boards: proposal accepted only if it remains in the SAT cache.
        UNSAT boards: proposal accepted only if it does not accidentally enter
                    the SAT cache (mirrors the UNSAT branch of walk()).

        Invalid proposals (wrong feasibility class) are silently rejected and
        the original board is returned unchanged — exactly the behaviour of
        a Metropolis step with zero acceptance probability.
        """
        B = labels.shape[0]
        device = labels.device

        with torch.no_grad():
            flat   = labels.view(B, 16).clone()                # [B, 16]

            # Pick one random cell per board
            cell   = torch.randint(0, 16, (B,), device=device) # [B]
            b_idx  = torch.arange(B, device=device)

            cur    = flat[b_idx, cell]                         # [B]  current digit (1..4)

            # New digit: uniform over {1,2,3,4} \ {cur}
            # offset in {1,2,3} then shift past cur, mod 4, back to 1-indexed
            offset = torch.randint(1, 4, (B,), device=device)  # [B]  in {1,2,3}
            new_digit = (cur - 1 + offset) % 4 + 1            # [B]  in {1,2,3,4}, != cur

            flat_prop = flat.clone()
            flat_prop[b_idx, cell] = new_digit
            proposals = flat_prop.view(B, 4, 4)                # [B, 4, 4]

            is_sat_proposal = self.tensor_check(proposals)     # [B] bool

            is_sat_board = board_labels.bool()                 # [B]

            # Accept conditions:
            #   SAT  boards → proposal must also be SAT
            #   UNSAT boards → proposal must remain UNSAT
            accept = torch.where(is_sat_board, is_sat_proposal, ~is_sat_proposal)

            result = torch.where(
                accept.unsqueeze(-1).unsqueeze(-1).expand_as(proposals),
                proposals,
                labels,
            )

        return result

# ---------------------------------------------------------------------- #
#  Quick smoke test                                                        #
# ---------------------------------------------------------------------- #

if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Enumerating all 4x4 Sudoku solutions...")
    sampler = Sampler()
    print(f"  Found {sampler.num_sat} SAT boards (expected 288).")

    B, K = 8, 3

    sat_boards = sampler.tensor_sat_sample_batch(device, batch_size=B, k=K)
    print(f"\nSAT sample  shape : {sat_boards.shape}")
    sat_valid = sampler.tensor_check(sat_boards.view(B * K, 4, 4))
    print(f"  All valid?       : {sat_valid.all().item()}")

    unsat_boards = sampler.tensor_unsat_sample_batch(device, batch_size=B, k=K)
    print(f"\nUNSAT sample shape : {unsat_boards.shape}")
    unsat_valid = sampler.tensor_check(unsat_boards.view(B * K, 4, 4))
    print(f"  Any valid?       : {unsat_valid.any().item()}  (should be False)")

    print("\nExample UNSAT board:")
    print(unsat_boards[0, 0])

    one_step_sat_boards = sampler.walk(sat_boards.view(-1, 4, 4), torch.tensor([1,1,1,1,1,1,1,1]))
    one_step_sat_boards = one_step_sat_boards.view(B, K, 4, 4)
    print(sat_boards[0, 0], sampler.tensor_check(sat_boards[0, 0].unsqueeze(0)))
    print(one_step_sat_boards[0, 0], sampler.tensor_check(one_step_sat_boards[0, 0].unsqueeze(0)))  